[features]
seeds = false
skip-lint = false
[programs.devnet]
anchor_marketplace = "8v2rU3yAxL1qxURQcvE1mfkexMjJMKWAxwmixB33z7Xi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/ivmidable/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
